# -*- coding: utf-8 -*-

# synctags.py - tag di sincronizzazione
# (c) 2020 Riccardo Polignieri

"""\
Tag di sincronizzazione.
========================

Questo file contiene i "tag di sincronizzazione" (synctag) per la 
traduzione italiana della documentazione ufficiale di Python. 

Per una spiegazione più dettagliata di tutto questo, 
vedi ``metadocs/sync.rst``.

Che cosa contiene questo file.
------------------------------

La variabile ``synctags`` riporta tutti i file della documentazione. 
Inoltre, 

- riporta il synctag dei file che non possono averlo internamente; 
- riporta ``None, None`` per i file che hanno il proprio synctag interno; 
- riporta ``"-", "-"`` per i file mantenuti in sincrono "per sezione";
- riporta ``None, None`` per gli ``index.rst`` di queste sezioni. 

Si noti che questo elenco non dice nulla sui file che hanno un synctag 
interno (contrassegnati qui con ``None, None``): questi file potrebbero 
non essere stati ancora tradotti, e avere quindi un synctag interno del 
tipo ``commit: XXX | data: XXX``. 

La variabile ``funny_synctags`` elenca i file "irregolari" che sono 
fuori posto rispetto alla repository originale CPython (si veda sempre 
``sync.rst`` per i dettagli).
"""

synctags = [
    # filename, commit hash, commit date
    ['Doc/about.rst', 'b7354a65ce7', '2014-10-29'], 
    ['Doc/bugs.rst', None, None], 
    ['Doc/conf.py', '423e77d6de4', '2020-08-12'], 
    ['Doc/contents.rst', None, None], 
    ['Doc/copyright.rst', '946b29ea0b3', '2020-01-02'], 
    ['Doc/glossary.rst', None, None], 
    ['Doc/license.rst', None, None], 
    ['Doc/make.bat', 'fe5dd78182d', '2020-06-01'], 
    ['Doc/Makefile', '8394500cca5', '2020-09-18'], 
    ['Doc/README.rst', '46ed90dd014', '2019-05-29'], 
    ['Doc/requirements.txt', '8394500cca5', '2020-09-18'], 
    ['Doc/runtime.txt', '87bc3b7a0b0', '2019-08-21'], 

    ['Doc/c-api/abstract.rst', None, None], 
    ['Doc/c-api/allocation.rst', None, None], 
    ['Doc/c-api/apiabiversion.rst', None, None], 
    ['Doc/c-api/arg.rst', None, None], 
    ['Doc/c-api/bool.rst', None, None], 
    ['Doc/c-api/buffer.rst', None, None], 
    ['Doc/c-api/bytearray.rst', None, None], 
    ['Doc/c-api/bytes.rst', None, None], 
    ['Doc/c-api/call.rst', None, None], 
    ['Doc/c-api/capsule.rst', None, None], 
    ['Doc/c-api/cell.rst', None, None], 
    ['Doc/c-api/code.rst', None, None], 
    ['Doc/c-api/codec.rst', None, None], 
    ['Doc/c-api/complex.rst', None, None], 
    ['Doc/c-api/concrete.rst', None, None], 
    ['Doc/c-api/contextvars.rst', None, None], 
    ['Doc/c-api/conversion.rst', None, None], 
    ['Doc/c-api/coro.rst', None, None], 
    ['Doc/c-api/datetime.rst', None, None], 
    ['Doc/c-api/decimal.rst', None, None], 
    ['Doc/c-api/descriptor.rst', None, None], 
    ['Doc/c-api/dict.rst', None, None], 
    ['Doc/c-api/exceptions.rst', None, None], 
    ['Doc/c-api/file.rst', None, None], 
    ['Doc/c-api/float.rst', None, None], 
    ['Doc/c-api/function.rst', None, None], 
    ['Doc/c-api/gcsupport.rst', None, None], 
    ['Doc/c-api/gen.rst', None, None], 
    ['Doc/c-api/import.rst', None, None], 
    ['Doc/c-api/index.rst', None, None], 
    ['Doc/c-api/init.rst', None, None], 
    ['Doc/c-api/init_config.rst', None, None], 
    ['Doc/c-api/intro.rst', None, None], 
    ['Doc/c-api/iter.rst', None, None], 
    ['Doc/c-api/iterator.rst', None, None], 
    ['Doc/c-api/list.rst', None, None], 
    ['Doc/c-api/long.rst', None, None], 
    ['Doc/c-api/mapping.rst', None, None], 
    ['Doc/c-api/marshal.rst', None, None], 
    ['Doc/c-api/memory.rst', None, None], 
    ['Doc/c-api/memoryview.rst', None, None], 
    ['Doc/c-api/method.rst', None, None], 
    ['Doc/c-api/module.rst', None, None], 
    ['Doc/c-api/none.rst', None, None], 
    ['Doc/c-api/number.rst', None, None], 
    ['Doc/c-api/object.rst', None, None], 
    ['Doc/c-api/objimpl.rst', None, None], 
    ['Doc/c-api/refcounting.rst', None, None], 
    ['Doc/c-api/reflection.rst', None, None], 
    ['Doc/c-api/sequence.rst', None, None], 
    ['Doc/c-api/set.rst', None, None], 
    ['Doc/c-api/slice.rst', None, None], 
    ['Doc/c-api/stable.rst', None, None], 
    ['Doc/c-api/structures.rst', None, None], 
    ['Doc/c-api/sys.rst', None, None], 
    ['Doc/c-api/tuple.rst', None, None], 
    ['Doc/c-api/type.rst', None, None], 
    ['Doc/c-api/typeobj.rst', None, None], 
    ['Doc/c-api/unicode.rst', None, None], 
    ['Doc/c-api/utilities.rst', None, None], 
    ['Doc/c-api/veryhigh.rst', None, None], 
    ['Doc/c-api/weakref.rst', None, None], 

    ['Doc/data/refcounts.dat', '037245c5ac4', '2020-10-09'], 

    ['Doc/distributing/index.rst', None, None], 

    ['Doc/distutils/apiref.rst', "-", "-"], 
    ['Doc/distutils/builtdist.rst', "-", "-"], 
    ['Doc/distutils/commandref.rst', "-", "-"], 
    ['Doc/distutils/configfile.rst', "-", "-"], 
    ['Doc/distutils/examples.rst', "-", "-"], 
    ['Doc/distutils/extending.rst', "-", "-"], 
    ['Doc/distutils/index.rst', None, None], 
    ['Doc/distutils/introduction.rst', "-", "-"], 
    ['Doc/distutils/packageindex.rst', "-", "-"], 
    ['Doc/distutils/setupscript.rst', "-", "-"], 
    ['Doc/distutils/sourcedist.rst', "-", "-"], 
    ['Doc/distutils/uploading.rst', "-", "-"], 
    ['Doc/distutils/_setuptools_disclaimer.rst', "-", "-"], 

    ['Doc/extending/building.rst', "-", "-"], 
    ['Doc/extending/embedding.rst', "-", "-"], 
    ['Doc/extending/extending.rst', "-", "-"], 
    ['Doc/extending/index.rst', None, None], 
    ['Doc/extending/newtypes.rst', "-", "-"], 
    ['Doc/extending/newtypes_tutorial.rst', "-", "-"], 
    ['Doc/extending/windows.rst', "-", "-"], 

    ['Doc/faq/design.rst', "-", "-"], 
    ['Doc/faq/extending.rst', "-", "-"], 
    ['Doc/faq/general.rst', "-", "-"], 
    ['Doc/faq/gui.rst', "-", "-"], 
    ['Doc/faq/index.rst', None, None], 
    ['Doc/faq/installed.rst', "-", "-"], 
    ['Doc/faq/library.rst', "-", "-"], 
    ['Doc/faq/programming.rst', "-", "-"], 
    ['Doc/faq/python-video-icon.png', "-", "-"], 
    ['Doc/faq/windows.rst', "-", "-"], 

    ['Doc/howto/argparse.rst', None, None], 
    ['Doc/howto/clinic.rst', None, None], 
    ['Doc/howto/cporting.rst', None, None], 
    ['Doc/howto/curses.rst', None, None], 
    ['Doc/howto/descriptor.rst', None, None], 
    ['Doc/howto/functional.rst', None, None], 
    ['Doc/howto/index.rst', None, None], 
    ['Doc/howto/instrumentation.rst', None, None], 
    ['Doc/howto/ipaddress.rst', None, None], 
    ['Doc/howto/logging-cookbook.rst', None, None], 
    ['Doc/howto/logging.rst', None, None], 
    ['Doc/howto/logging_flow.png', 'c6cd164cffe', '2018-07-01'], 
    ['Doc/howto/pyporting.rst', None, None], 
    ['Doc/howto/regex.rst', None, None], 
    ['Doc/howto/sockets.rst', None, None], 
    ['Doc/howto/sorting.rst', None, None], 
    ['Doc/howto/unicode.rst', None, None], 
    ['Doc/howto/urllib2.rst', None, None], 

    ['Doc/includes/custom.c', '5c7ed7550ec', '2019-12-24'], 
    ['Doc/includes/custom2.c', '224b8aaa7e8', '2019-09-12'], 
    ['Doc/includes/custom3.c', '224b8aaa7e8', '2019-09-12'], 
    ['Doc/includes/custom4.c', '224b8aaa7e8', '2019-09-12'], 
    ['Doc/includes/dbpickle.py', '40fc59d98b7', '2011-04-26'], 
    ['Doc/includes/email-alternative.py', '8337239d792', '2017-09-24'], 
    ['Doc/includes/email-dir.py', 'e8acc865a3f', '2019-11-15'], 
    ['Doc/includes/email-headers.py', '29d1bc0842e', '2016-09-07'], 
    ['Doc/includes/email-mime.py', '8efade91b12', '2019-07-14'], 
    ['Doc/includes/email-read-alternative.py', '53f7a7c2814', '2017-12-14'], 
    ['Doc/includes/email-simple.py', 'e8acc865a3f', '2019-11-15'], 
    ['Doc/includes/email-unpack.py', 'e8acc865a3f', '2019-11-15'], 
    ['Doc/includes/minidom-example.py', '2614cda2091', '2010-03-21'], 
    ['Doc/includes/mp_newtype.py', '84ed9a68bd9', '2013-08-14'], 
    ['Doc/includes/mp_pool.py', '84ed9a68bd9', '2013-08-14'], 
    ['Doc/includes/mp_workers.py', '84ed9a68bd9', '2013-08-14'], 
    ['Doc/includes/run-func.c', 'c88feceb449', '2019-04-13'], 
    ['Doc/includes/setup.py', 'fb8fe72fc59', '2017-02-21'], 
    ['Doc/includes/sublist.c', '224b8aaa7e8', '2019-09-12'], 
    ['Doc/includes/test.py', '1d80a561734', '2018-04-07'], 
    ['Doc/includes/turtle-star.py', '14fb79977b0', '2010-11-09'], 
    ['Doc/includes/typestruct.h', '9e3e06e582a', '2019-06-03'], 
    ['Doc/includes/tzinfo_examples.py', '3a9bb5f269c', '2018-07-05'], 
    ['Doc/includes/sqlite3/adapter_datetime.py', '287b84de939', '2019-05-20'], 
    ['Doc/includes/sqlite3/adapter_point_1.py', '287b84de939', '2019-05-20'], 
    ['Doc/includes/sqlite3/adapter_point_2.py', '287b84de939', '2019-05-20'], 
    ['Doc/includes/sqlite3/collation_reverse.py', 'c48d8340268', '2009-02-01'], 
    ['Doc/includes/sqlite3/complete_statement.py', '116aa62bf54', '2007-08-15'], 
    ['Doc/includes/sqlite3/converter_point.py', '1ca93954e17', '2012-02-15'], 
    ['Doc/includes/sqlite3/countcursors.py', '287b84de939', '2019-05-20'], 
    ['Doc/includes/sqlite3/createdb.py', '116aa62bf54', '2007-08-15'], 
    ['Doc/includes/sqlite3/ctx_manager.py', '287b84de939', '2019-05-20'], 
    ['Doc/includes/sqlite3/execsql_fetchonerow.py', '287b84de939', '2019-05-20'], 
    ['Doc/includes/sqlite3/execsql_printall_1.py', '287b84de939', '2019-05-20'], 
    ['Doc/includes/sqlite3/executemany_1.py', '287b84de939', '2019-05-20'], 
    ['Doc/includes/sqlite3/executemany_2.py', '287b84de939', '2019-05-20'], 
    ['Doc/includes/sqlite3/executescript.py', '287b84de939', '2019-05-20'], 
    ['Doc/includes/sqlite3/execute_1.py', '287b84de939', '2019-05-20'], 
    ['Doc/includes/sqlite3/insert_more_people.py', '287b84de939', '2019-05-20'], 
    ['Doc/includes/sqlite3/load_extension.py', '287b84de939', '2019-05-20'], 
    ['Doc/includes/sqlite3/md5func.py', '287b84de939', '2019-05-20'], 
    ['Doc/includes/sqlite3/mysumaggr.py', '287b84de939', '2019-05-20'], 
    ['Doc/includes/sqlite3/parse_colnames.py', '287b84de939', '2019-05-20'], 
    ['Doc/includes/sqlite3/pysqlite_datetime.py', '287b84de939', '2019-05-20'], 
    ['Doc/includes/sqlite3/rowclass.py', '287b84de939', '2019-05-20'], 
    ['Doc/includes/sqlite3/row_factory.py', '287b84de939', '2019-05-20'], 
    ['Doc/includes/sqlite3/shared_cache.py', '13925008dc1', '2011-03-16'], 
    ['Doc/includes/sqlite3/shortcut_methods.py', '287b84de939', '2019-05-20'], 
    ['Doc/includes/sqlite3/simple_tableprinter.py', '287b84de939', '2019-05-20'], 
    ['Doc/includes/sqlite3/text_factory.py', '287b84de939', '2019-05-20'], 

    ['Doc/install/index.rst', None, None], 

    ['Doc/installing/index.rst', None, None], 

    ['Doc/library/2to3.rst', None, None], 
    ['Doc/library/abc.rst', None, None], 
    ['Doc/library/aifc.rst', None, None], 
    ['Doc/library/allos.rst', None, None], 
    ['Doc/library/archiving.rst', None, None], 
    ['Doc/library/argparse.rst', None, None], 
    ['Doc/library/array.rst', None, None], 
    ['Doc/library/ast.rst', None, None], 
    ['Doc/library/asynchat.rst', None, None], 
    ['Doc/library/asyncio-api-index.rst', None, None], 
    ['Doc/library/asyncio-dev.rst', None, None], 
    ['Doc/library/asyncio-eventloop.rst', None, None], 
    ['Doc/library/asyncio-exceptions.rst', None, None], 
    ['Doc/library/asyncio-future.rst', None, None], 
    ['Doc/library/asyncio-llapi-index.rst', None, None], 
    ['Doc/library/asyncio-platforms.rst', None, None], 
    ['Doc/library/asyncio-policy.rst', None, None], 
    ['Doc/library/asyncio-protocol.rst', None, None], 
    ['Doc/library/asyncio-queue.rst', None, None], 
    ['Doc/library/asyncio-stream.rst', None, None], 
    ['Doc/library/asyncio-subprocess.rst', None, None], 
    ['Doc/library/asyncio-sync.rst', None, None], 
    ['Doc/library/asyncio-task.rst', None, None], 
    ['Doc/library/asyncio.rst', None, None], 
    ['Doc/library/asyncore.rst', None, None], 
    ['Doc/library/atexit.rst', None, None], 
    ['Doc/library/audioop.rst', None, None], 
    ['Doc/library/audit_events.rst', None, None], 
    ['Doc/library/base64.rst', None, None], 
    ['Doc/library/bdb.rst', None, None], 
    ['Doc/library/binary.rst', None, None], 
    ['Doc/library/binascii.rst', None, None], 
    ['Doc/library/binhex.rst', None, None], 
    ['Doc/library/bisect.rst', None, None], 
    ['Doc/library/builtins.rst', None, None], 
    ['Doc/library/bz2.rst', None, None], 
    ['Doc/library/calendar.rst', None, None], 
    ['Doc/library/cgi.rst', None, None], 
    ['Doc/library/cgitb.rst', None, None], 
    ['Doc/library/chunk.rst', None, None], 
    ['Doc/library/cmath.rst', None, None], 
    ['Doc/library/cmd.rst', None, None], 
    ['Doc/library/code.rst', None, None], 
    ['Doc/library/codecs.rst', None, None], 
    ['Doc/library/codeop.rst', None, None], 
    ['Doc/library/collections.abc.rst', None, None], 
    ['Doc/library/collections.rst', None, None], 
    ['Doc/library/colorsys.rst', None, None], 
    ['Doc/library/compileall.rst', None, None], 
    ['Doc/library/concurrency.rst', None, None], 
    ['Doc/library/concurrent.futures.rst', None, None], 
    ['Doc/library/concurrent.rst', None, None], 
    ['Doc/library/configparser.rst', None, None], 
    ['Doc/library/constants.rst', None, None], 
    ['Doc/library/contextlib.rst', None, None], 
    ['Doc/library/contextvars.rst', None, None], 
    ['Doc/library/copy.rst', None, None], 
    ['Doc/library/copyreg.rst', None, None], 
    ['Doc/library/crypt.rst', None, None], 
    ['Doc/library/crypto.rst', None, None], 
    ['Doc/library/csv.rst', None, None], 
    ['Doc/library/ctypes.rst', None, None], 
    ['Doc/library/curses.ascii.rst', None, None], 
    ['Doc/library/curses.panel.rst', None, None], 
    ['Doc/library/curses.rst', None, None], 
    ['Doc/library/custominterp.rst', None, None], 
    ['Doc/library/dataclasses.rst', None, None], 
    ['Doc/library/datatypes.rst', None, None], 
    ['Doc/library/datetime.rst', None, None], 
    ['Doc/library/dbm.rst', None, None], 
    ['Doc/library/debug.rst', None, None], 
    ['Doc/library/decimal.rst', None, None], 
    ['Doc/library/development.rst', None, None], 
    ['Doc/library/devmode.rst', None, None], 
    ['Doc/library/dialog.rst', None, None], 
    ['Doc/library/difflib.rst', None, None], 
    ['Doc/library/dis.rst', None, None], 
    ['Doc/library/distribution.rst', None, None], 
    ['Doc/library/distutils.rst', None, None], 
    ['Doc/library/doctest.rst', None, None], 
    ['Doc/library/email.charset.rst', None, None], 
    ['Doc/library/email.compat32-message.rst', None, None], 
    ['Doc/library/email.contentmanager.rst', None, None], 
    ['Doc/library/email.encoders.rst', None, None], 
    ['Doc/library/email.errors.rst', None, None], 
    ['Doc/library/email.examples.rst', None, None], 
    ['Doc/library/email.generator.rst', None, None], 
    ['Doc/library/email.header.rst', None, None], 
    ['Doc/library/email.headerregistry.rst', None, None], 
    ['Doc/library/email.iterators.rst', None, None], 
    ['Doc/library/email.message.rst', None, None], 
    ['Doc/library/email.mime.rst', None, None], 
    ['Doc/library/email.parser.rst', None, None], 
    ['Doc/library/email.policy.rst', None, None], 
    ['Doc/library/email.rst', None, None], 
    ['Doc/library/email.utils.rst', None, None], 
    ['Doc/library/ensurepip.rst', None, None], 
    ['Doc/library/enum.rst', None, None], 
    ['Doc/library/errno.rst', None, None], 
    ['Doc/library/exceptions.rst', None, None], 
    ['Doc/library/faulthandler.rst', None, None], 
    ['Doc/library/fcntl.rst', None, None], 
    ['Doc/library/filecmp.rst', None, None], 
    ['Doc/library/fileformats.rst', None, None], 
    ['Doc/library/fileinput.rst', None, None], 
    ['Doc/library/filesys.rst', None, None], 
    ['Doc/library/fnmatch.rst', None, None], 
    ['Doc/library/formatter.rst', None, None], 
    ['Doc/library/fractions.rst', None, None], 
    ['Doc/library/frameworks.rst', None, None], 
    ['Doc/library/ftplib.rst', None, None], 
    ['Doc/library/functional.rst', None, None], 
    ['Doc/library/functions.rst', None, None], 
    ['Doc/library/functools.rst', None, None], 
    ['Doc/library/gc.rst', None, None], 
    ['Doc/library/getopt.rst', None, None], 
    ['Doc/library/getpass.rst', None, None], 
    ['Doc/library/gettext.rst', None, None], 
    ['Doc/library/glob.rst', None, None], 
    ['Doc/library/graphlib.rst', None, None], 
    ['Doc/library/grp.rst', None, None], 
    ['Doc/library/gzip.rst', None, None], 
    ['Doc/library/hashlib-blake2-tree.png', 'c6cd164cffe', '2018-07-01'], 
    ['Doc/library/hashlib.rst', None, None], 
    ['Doc/library/heapq.rst', None, None], 
    ['Doc/library/hmac.rst', None, None], 
    ['Doc/library/html.entities.rst', None, None], 
    ['Doc/library/html.parser.rst', None, None], 
    ['Doc/library/html.rst', None, None], 
    ['Doc/library/http.client.rst', None, None], 
    ['Doc/library/http.cookiejar.rst', None, None], 
    ['Doc/library/http.cookies.rst', None, None], 
    ['Doc/library/http.rst', None, None], 
    ['Doc/library/http.server.rst', None, None], 
    ['Doc/library/i18n.rst', None, None], 
    ['Doc/library/idle.rst', None, None], 
    ['Doc/library/imaplib.rst', None, None], 
    ['Doc/library/imghdr.rst', None, None], 
    ['Doc/library/imp.rst', None, None], 
    ['Doc/library/importlib.metadata.rst', None, None], 
    ['Doc/library/importlib.rst', None, None], 
    ['Doc/library/index.rst', None, None], 
    ['Doc/library/inspect.rst', None, None], 
    ['Doc/library/internet.rst', None, None], 
    ['Doc/library/intro.rst', None, None], 
    ['Doc/library/io.rst', None, None], 
    ['Doc/library/ipaddress.rst', None, None], 
    ['Doc/library/ipc.rst', None, None], 
    ['Doc/library/itertools.rst', None, None], 
    ['Doc/library/json.rst', None, None], 
    ['Doc/library/keyword.rst', None, None], 
    ['Doc/library/language.rst', None, None], 
    ['Doc/library/linecache.rst', None, None], 
    ['Doc/library/locale.rst', None, None], 
    ['Doc/library/logging.config.rst', None, None], 
    ['Doc/library/logging.handlers.rst', None, None], 
    ['Doc/library/logging.rst', None, None], 
    ['Doc/library/lzma.rst', None, None], 
    ['Doc/library/mailbox.rst', None, None], 
    ['Doc/library/mailcap.rst', None, None], 
    ['Doc/library/markup.rst', None, None], 
    ['Doc/library/marshal.rst', None, None], 
    ['Doc/library/math.rst', None, None], 
    ['Doc/library/mimetypes.rst', None, None], 
    ['Doc/library/misc.rst', None, None], 
    ['Doc/library/mm.rst', None, None], 
    ['Doc/library/mmap.rst', None, None], 
    ['Doc/library/modulefinder.rst', None, None], 
    ['Doc/library/modules.rst', None, None], 
    ['Doc/library/msilib.rst', None, None], 
    ['Doc/library/msvcrt.rst', None, None], 
    ['Doc/library/multiprocessing.rst', None, None], 
    ['Doc/library/multiprocessing.shared_memory.rst', None, None], 
    ['Doc/library/netdata.rst', None, None], 
    ['Doc/library/netrc.rst', None, None], 
    ['Doc/library/nis.rst', None, None], 
    ['Doc/library/nntplib.rst', None, None], 
    ['Doc/library/numbers.rst', None, None], 
    ['Doc/library/numeric.rst', None, None], 
    ['Doc/library/operator.rst', None, None], 
    ['Doc/library/optparse.rst', None, None], 
    ['Doc/library/os.path.rst', None, None], 
    ['Doc/library/os.rst', None, None], 
    ['Doc/library/ossaudiodev.rst', None, None], 
    ['Doc/library/othergui.rst', None, None], 
    ['Doc/library/pathlib-inheritance.png', 'cd90f6a3692', '2019-02-05'], 
    ['Doc/library/pathlib-inheritance.svg', 'cd90f6a3692', '2019-02-05'], 
    ['Doc/library/pathlib.rst', None, None], 
    ['Doc/library/pdb.rst', None, None], 
    ['Doc/library/persistence.rst', None, None], 
    ['Doc/library/pickle.rst', None, None], 
    ['Doc/library/pickletools.rst', None, None], 
    ['Doc/library/pipes.rst', None, None], 
    ['Doc/library/pkgutil.rst', None, None], 
    ['Doc/library/platform.rst', None, None], 
    ['Doc/library/plistlib.rst', None, None], 
    ['Doc/library/poplib.rst', None, None], 
    ['Doc/library/posix.rst', None, None], 
    ['Doc/library/pprint.rst', None, None], 
    ['Doc/library/profile.rst', None, None], 
    ['Doc/library/pty.rst', None, None], 
    ['Doc/library/pwd.rst', None, None], 
    ['Doc/library/pyclbr.rst', None, None], 
    ['Doc/library/pydoc.rst', None, None], 
    ['Doc/library/pyexpat.rst', None, None], 
    ['Doc/library/python.rst', None, None], 
    ['Doc/library/py_compile.rst', None, None], 
    ['Doc/library/queue.rst', None, None], 
    ['Doc/library/quopri.rst', None, None], 
    ['Doc/library/random.rst', None, None], 
    ['Doc/library/re.rst', None, None], 
    ['Doc/library/readline.rst', None, None], 
    ['Doc/library/reprlib.rst', None, None], 
    ['Doc/library/resource.rst', None, None], 
    ['Doc/library/rlcompleter.rst', None, None], 
    ['Doc/library/runpy.rst', None, None], 
    ['Doc/library/sched.rst', None, None], 
    ['Doc/library/secrets.rst', None, None], 
    ['Doc/library/select.rst', None, None], 
    ['Doc/library/selectors.rst', None, None], 
    ['Doc/library/shelve.rst', None, None], 
    ['Doc/library/shlex.rst', None, None], 
    ['Doc/library/shutil.rst', None, None], 
    ['Doc/library/signal.rst', None, None], 
    ['Doc/library/site.rst', None, None], 
    ['Doc/library/smtpd.rst', None, None], 
    ['Doc/library/smtplib.rst', None, None], 
    ['Doc/library/sndhdr.rst', None, None], 
    ['Doc/library/socket.rst', None, None], 
    ['Doc/library/socketserver.rst', None, None], 
    ['Doc/library/spwd.rst', None, None], 
    ['Doc/library/sqlite3.rst', None, None], 
    ['Doc/library/ssl.rst', None, None], 
    ['Doc/library/stat.rst', None, None], 
    ['Doc/library/statistics.rst', None, None], 
    ['Doc/library/stdtypes.rst', None, None], 
    ['Doc/library/string.rst', None, None], 
    ['Doc/library/stringprep.rst', None, None], 
    ['Doc/library/struct.rst', None, None], 
    ['Doc/library/subprocess.rst', None, None], 
    ['Doc/library/sunau.rst', None, None], 
    ['Doc/library/superseded.rst', None, None], 
    ['Doc/library/symtable.rst', None, None], 
    ['Doc/library/sys.rst', None, None], 
    ['Doc/library/sysconfig.rst', None, None], 
    ['Doc/library/syslog.rst', None, None], 
    ['Doc/library/tabnanny.rst', None, None], 
    ['Doc/library/tarfile.rst', None, None], 
    ['Doc/library/telnetlib.rst', None, None], 
    ['Doc/library/tempfile.rst', None, None], 
    ['Doc/library/termios.rst', None, None], 
    ['Doc/library/test.rst', None, None], 
    ['Doc/library/text.rst', None, None], 
    ['Doc/library/textwrap.rst', None, None], 
    ['Doc/library/threading.rst', None, None], 
    ['Doc/library/time.rst', None, None], 
    ['Doc/library/timeit.rst', None, None], 
    ['Doc/library/tk.rst', None, None], 
    ['Doc/library/tkinter.colorchooser.rst', None, None], 
    ['Doc/library/tkinter.dnd.rst', None, None], 
    ['Doc/library/tkinter.font.rst', None, None], 
    ['Doc/library/tkinter.messagebox.rst', None, None], 
    ['Doc/library/tkinter.rst', None, None], 
    ['Doc/library/tkinter.scrolledtext.rst', None, None], 
    ['Doc/library/tkinter.tix.rst', None, None], 
    ['Doc/library/tkinter.ttk.rst', None, None], 
    ['Doc/library/tk_msg.png', '80428ed4e19', '2019-09-10'], 
    ['Doc/library/token-list.inc', '495da292255', '2019-03-07'], 
    ['Doc/library/token.rst', None, None], 
    ['Doc/library/tokenize.rst', None, None], 
    ['Doc/library/trace.rst', None, None], 
    ['Doc/library/traceback.rst', None, None], 
    ['Doc/library/tracemalloc.rst', None, None], 
    ['Doc/library/tty.rst', None, None], 
    ['Doc/library/tulip_coro.dia', 'edb09c5c0b1', '2015-06-25'], 
    ['Doc/library/tulip_coro.png', 'c6cd164cffe', '2018-07-01'], 
    ['Doc/library/turtle-star.pdf', '14fb79977b0', '2010-11-09'], 
    ['Doc/library/turtle-star.png', 'c6cd164cffe', '2018-07-01'], 
    ['Doc/library/turtle-star.ps', '14fb79977b0', '2010-11-09'], 
    ['Doc/library/turtle.rst', None, None], 
    ['Doc/library/types.rst', None, None], 
    ['Doc/library/typing.rst', None, None], 
    ['Doc/library/undoc.rst', None, None], 
    ['Doc/library/unicodedata.rst', None, None], 
    ['Doc/library/unittest.mock-examples.rst', None, None], 
    ['Doc/library/unittest.mock.rst', None, None], 
    ['Doc/library/unittest.rst', None, None], 
    ['Doc/library/unix.rst', None, None], 
    ['Doc/library/urllib.error.rst', None, None], 
    ['Doc/library/urllib.parse.rst', None, None], 
    ['Doc/library/urllib.request.rst', None, None], 
    ['Doc/library/urllib.robotparser.rst', None, None], 
    ['Doc/library/urllib.rst', None, None], 
    ['Doc/library/uu.rst', None, None], 
    ['Doc/library/uuid.rst', None, None], 
    ['Doc/library/venv.rst', None, None], 
    ['Doc/library/warnings.rst', None, None], 
    ['Doc/library/wave.rst', None, None], 
    ['Doc/library/weakref.rst', None, None], 
    ['Doc/library/webbrowser.rst', None, None], 
    ['Doc/library/windows.rst', None, None], 
    ['Doc/library/winreg.rst', None, None], 
    ['Doc/library/winsound.rst', None, None], 
    ['Doc/library/wsgiref.rst', None, None], 
    ['Doc/library/xdrlib.rst', None, None], 
    ['Doc/library/xml.dom.minidom.rst', None, None], 
    ['Doc/library/xml.dom.pulldom.rst', None, None], 
    ['Doc/library/xml.dom.rst', None, None], 
    ['Doc/library/xml.etree.elementtree.rst', None, None], 
    ['Doc/library/xml.rst', None, None], 
    ['Doc/library/xml.sax.handler.rst', None, None], 
    ['Doc/library/xml.sax.reader.rst', None, None], 
    ['Doc/library/xml.sax.rst', None, None], 
    ['Doc/library/xml.sax.utils.rst', None, None], 
    ['Doc/library/xmlrpc.client.rst', None, None], 
    ['Doc/library/xmlrpc.rst', None, None], 
    ['Doc/library/xmlrpc.server.rst', None, None], 
    ['Doc/library/zipapp.rst', None, None], 
    ['Doc/library/zipfile.rst', None, None], 
    ['Doc/library/zipimport.rst', None, None], 
    ['Doc/library/zlib.rst', None, None], 
    ['Doc/library/zoneinfo.rst', None, None], 
    ['Doc/library/_thread.rst', None, None], 
    ['Doc/library/__future__.rst', None, None], 
    ['Doc/library/__main__.rst', None, None], 

    ['Doc/reference/compound_stmts.rst', "-", "-"], 
    ['Doc/reference/datamodel.rst', "-", "-"], 
    ['Doc/reference/executionmodel.rst', "-", "-"], 
    ['Doc/reference/expressions.rst', "-", "-"], 
    ['Doc/reference/grammar.rst', "-", "-"], 
    ['Doc/reference/import.rst', "-", "-"], 
    ['Doc/reference/index.rst', None, None], 
    ['Doc/reference/introduction.rst', "-", "-"], 
    ['Doc/reference/lexical_analysis.rst', "-", "-"], 
    ['Doc/reference/simple_stmts.rst', "-", "-"], 
    ['Doc/reference/toplevel_components.rst', "-", "-"], 

    ['Doc/tools/rstlint.py', '2d6097d027e', '2018-10-12'], 
    ['Doc/tools/susp-ignored.csv', '13d52c26869', '2020-03-10'], 
    ['Doc/tools/extensions/asdl_highlight.py', '7f03445d01d', '2020-07-20'], 
    ['Doc/tools/extensions/c_annotations.py', '83dd4e87a62', '2018-12-20'], 
    ['Doc/tools/extensions/escape4chm.py', 'afe17a7bee1', '2018-12-19'], 
    ['Doc/tools/extensions/patchlevel.py', 'ba964cc5f73', '2017-01-29'], 
    ['Doc/tools/extensions/peg_highlight.py', 'a5634c40676', '2020-09-16'], 
    ['Doc/tools/extensions/pyspecific.py', '6595cb0af4c', '2020-09-18'], 
    ['Doc/tools/extensions/suspicious.py', 'e1786b54162', '2019-09-02'], 
    ['Doc/tools/static/changelog_search.js', 'bf63e8d55fd', '2018-03-01'], 
    ['Doc/tools/static/switchers.js', '19e3e002641', '2020-05-19'], 
    ['Doc/tools/templates/customsourcelink.html', 'b9ff4987936', '2017-08-18'], 
    ['Doc/tools/templates/download.html', '39c34933fc9', '2020-03-11'], 
    ['Doc/tools/templates/dummy.html', '735d902b363', '2020-05-30'], 
    ['Doc/tools/templates/indexcontent.html', '081158e3ba2', '2019-03-28'], 
    ['Doc/tools/templates/indexsidebar.html', '19e3e002641', '2020-05-19'], 
    ['Doc/tools/templates/layout.html', '552951563cd', '2019-06-16'], 
    ['Doc/tools/templates/opensearch.xml', '46761ec7c29', '2014-10-29'], 

    ['Doc/tutorial/appendix.rst', "-", "-"], 
    ['Doc/tutorial/appetite.rst', "-", "-"], 
    ['Doc/tutorial/classes.rst', "-", "-"], 
    ['Doc/tutorial/controlflow.rst', "-", "-"], 
    ['Doc/tutorial/datastructures.rst', "-", "-"], 
    ['Doc/tutorial/errors.rst', "-", "-"], 
    ['Doc/tutorial/floatingpoint.rst', "-", "-"], 
    ['Doc/tutorial/index.rst', None, None], 
    ['Doc/tutorial/inputoutput.rst', "-", "-"], 
    ['Doc/tutorial/interactive.rst', "-", "-"], 
    ['Doc/tutorial/interpreter.rst', "-", "-"], 
    ['Doc/tutorial/introduction.rst', "-", "-"], 
    ['Doc/tutorial/modules.rst', "-", "-"], 
    ['Doc/tutorial/stdlib.rst', "-", "-"], 
    ['Doc/tutorial/stdlib2.rst', "-", "-"], 
    ['Doc/tutorial/venv.rst', "-", "-"], 
    ['Doc/tutorial/whatnow.rst', "-", "-"], 

    ['Doc/using/cmdline.rst', "-", "-"], 
    ['Doc/using/editors.rst', "-", "-"], 
    ['Doc/using/index.rst', None, None], 
    ['Doc/using/mac.rst', "-", "-"], 
    ['Doc/using/unix.rst', "-", "-"], 
    ['Doc/using/venv-create.inc', "-", "-"], 
    ['Doc/using/windows.rst', "-", "-"], 
    ['Doc/using/win_installer.png', "-", "-"], 

    ['Doc/whatsnew/2.0.rst', None, None], 
    ['Doc/whatsnew/2.1.rst', None, None], 
    ['Doc/whatsnew/2.2.rst', None, None], 
    ['Doc/whatsnew/2.3.rst', None, None], 
    ['Doc/whatsnew/2.4.rst', None, None], 
    ['Doc/whatsnew/2.5.rst', None, None], 
    ['Doc/whatsnew/2.6.rst', None, None], 
    ['Doc/whatsnew/2.7.rst', None, None], 
    ['Doc/whatsnew/3.0.rst', None, None], 
    ['Doc/whatsnew/3.1.rst', None, None], 
    ['Doc/whatsnew/3.10.rst', None, None], 
    ['Doc/whatsnew/3.2.rst', None, None], 
    ['Doc/whatsnew/3.3.rst', None, None], 
    ['Doc/whatsnew/3.4.rst', None, None], 
    ['Doc/whatsnew/3.5.rst', None, None], 
    ['Doc/whatsnew/3.6.rst', None, None], 
    ['Doc/whatsnew/3.7.rst', None, None], 
    ['Doc/whatsnew/3.8.rst', None, None], 
    ['Doc/whatsnew/3.9.rst', None, None], 
    ['Doc/whatsnew/changelog.rst', None, None], 
    ['Doc/whatsnew/index.rst', None, None], 
]

funny_synctags = [
    # filename, original filename, commit hash, commit date
    ['Doc/Parser/peg_api.c', 'Parser/peg_api.c', '564cd187677', '2020-06-22'], 
    ['Doc/Parser/pegen.c', 'Parser/pegen.c', 'a5634c40676', '2020-09-16'], 
    ['Doc/Parser/pegen.h', 'Parser/pegen.h', 'a5634c40676', '2020-09-16'], 
    ['Doc/Parser/Python.asdl', 'Parser/Python.asdl', '091951a67c8', '2020-05-06'], 
    ['Doc/Parser/string_parser.c', 'Parser/string_parser.c', 'a5634c40676', '2020-09-16'], 
    ['Doc/Parser/string_parser.h', 'Parser/string_parser.h', '1ed83adb0e9', '2020-06-11'], 
    ['Doc/Parser/token.c', 'Parser/token.c', '495da292255', '2019-03-07'], 
    ['Doc/Parser/tokenizer.c', 'Parser/tokenizer.c', 'e822e37946f', '2020-06-15'], 
    ['Doc/Parser/tokenizer.h', 'Parser/tokenizer.h', '384f3c536dd', '2020-02-27'], 
    ['Doc/Parser/asdl.py', 'Parser/asdl.py', '091951a67c8', '2020-05-06'], 
    ['Doc/Parser/asdl_c.py', 'Parser/asdl_c.py', 'a5634c40676', '2020-09-16'], 
    ['Doc/Parser/myreadline.c', 'Parser/myreadline.c', 'bde48fd8110', '2020-08-04'], 
    ['Doc/Parser/parser.c', 'Parser/parser.c', '48f305fd122', '2020-10-09'], 

    ['Doc/Parser/patchlevel.h', 'Include/patchlevel.h', '91e33390663', '2020-10-05'], 
]
